name: Update Guangdong Fuel Price

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 北京时间 08:00

# 关键：给 GITHUB_TOKEN 写入代码的权限
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update JSON
        run: |
          mkdir -p data
          cat > data/guangdong_fuel.json <<'EOF'
          {
            "province": "广东",
            "updated_at": "__WILL_BE_REPLACED__",
            "unit": "元/升",
            "items": [
              { "name": "92#", "price": 7.13 },
              { "name": "95#", "price": 7.73 },
              { "name": "98#", "price": 9.73 },
              { "name": "0# 柴油", "price": 6.76 }
            ],
            "source": "Actions 自动更新 (示例数据)"
          }
          EOF
          # 用当前时间替换占位符
          sed -i "s/__WILL_BE_REPLACED__/$(date '+%Y-%m-%d %H:%M:%S')/g" data/guangdong_fuel.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/guangdong_fuel.json
          git commit -m "Auto update Guangdong fuel price" || echo "No changes to commit"
          git push
